apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.mqttName }}
  namespace: azure-iot-operations
spec:
  # Use the "mqtt-client" service account which comes with default deployment
  # Otherwise create it with `kubectl create serviceaccount mqtt-client -n azure-iot-operations`
  serviceAccountName: mqtt-client
  containers:
  - image: cesicontainerregistry.azurecr.io/mqtt-client
    name: {{ .Values.mqttName }}
    command: ["sh", "-c"]
    args: ["sleep infinity"]
  imagePullSecrets:
  - name: regcred