apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-arc
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 5m
  releaseName: hello-cesi
  chart:
    spec:
      chart: ./mercer-deployment/
